services:
  app:
    image: 'b358b70cfd60'
    build: .
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root